package com.example.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import greendao.User;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER".
*/
public class UserDao extends AbstractDao<User, Long> {

    public static final String TABLENAME = "USER";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Uid = new Property(2, String.class, "uid", false, "UID");
        public final static Property Egpoint = new Property(3, Double.class, "egpoint", false, "EGPOINT");
        public final static Property GameId = new Property(4, Long.class, "gameId", false, "GAME_ID");
        public final static Property ServerId = new Property(5, String.class, "serverId", false, "SERVER_ID");
        public final static Property RoleId = new Property(6, String.class, "roleId", false, "ROLE_ID");
        public final static Property Level = new Property(7, int.class, "level", false, "LEVEL");
    }


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"UID\" TEXT UNIQUE ," + // 2: uid
                "\"EGPOINT\" REAL," + // 3: egpoint
                "\"GAME_ID\" INTEGER," + // 4: gameId
                "\"SERVER_ID\" TEXT," + // 5: serverId
                "\"ROLE_ID\" TEXT," + // 6: roleId
                "\"LEVEL\" INTEGER NOT NULL );"); // 7: level
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String uid = entity.getUid();
        if (uid != null) {
            stmt.bindString(3, uid);
        }
 
        Double egpoint = entity.getEgpoint();
        if (egpoint != null) {
            stmt.bindDouble(4, egpoint);
        }
 
        Long gameId = entity.getGameId();
        if (gameId != null) {
            stmt.bindLong(5, gameId);
        }
 
        String serverId = entity.getServerId();
        if (serverId != null) {
            stmt.bindString(6, serverId);
        }
 
        String roleId = entity.getRoleId();
        if (roleId != null) {
            stmt.bindString(7, roleId);
        }
        stmt.bindLong(8, entity.getLevel());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String uid = entity.getUid();
        if (uid != null) {
            stmt.bindString(3, uid);
        }
 
        Double egpoint = entity.getEgpoint();
        if (egpoint != null) {
            stmt.bindDouble(4, egpoint);
        }
 
        Long gameId = entity.getGameId();
        if (gameId != null) {
            stmt.bindLong(5, gameId);
        }
 
        String serverId = entity.getServerId();
        if (serverId != null) {
            stmt.bindString(6, serverId);
        }
 
        String roleId = entity.getRoleId();
        if (roleId != null) {
            stmt.bindString(7, roleId);
        }
        stmt.bindLong(8, entity.getLevel());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // uid
            cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3), // egpoint
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // gameId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // serverId
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // roleId
            cursor.getInt(offset + 7) // level
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUid(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setEgpoint(cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3));
        entity.setGameId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setServerId(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setRoleId(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setLevel(cursor.getInt(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(User entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(User entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(User entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
